### ISSUE TITLE
Add option for rainbow dogs

### ISSUE THREAD

**Issue by jonathan-d-zhang** [letsbuilda/clidogs#10]
Why? It would be cool.

Specific idea? Move the random coloring to a CLI option, making the default color just black and white. Also add rainbow coloring as a CLI option.

Would also be ok if the default was the random colors.

**Comment by shenanigansd** [comment]
Makes sense, I agree
I think I'd go with black and white as the default, to avoid breaking things on terminals that don't support colors.
